dependencies:
- name: spinnaker
  version: 1.8.1
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: redis.enabled
- name: docker-registry
  version: 1.8.0
  repository: https://kubernetes-charts.storage.googleapis.com
