apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-credentials-pod
data:
  username: {{ .Values.registry.username | b64enc }}
  password: {{ .Values.registry.password | b64enc }}
  server: {{ .Values.registry.server | b64enc }}
  email: {{ .Values.registry.email | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: github-credentials
data:
  username: {{ .Values.github.username | b64enc }}
  password: {{ .Values.github.password | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: Siddhi-credentials
type: Opaque
data:
  username: {{ .Values.SiddhiUsername | b64enc }}
  password: {{ .Values.SiddhiPassword | b64enc }}
