# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: jenkins
#   labels:
#     type: local
# spec:
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/data/jenkins/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim
  labels:
    app: jenkins
    tier: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wum-claim
  labels:
    app: jenkins
    tier: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
